### ISSUE TITLE
prevents program from exiting

### ISSUE THREAD

**Issue by slang800** [namshi/winston-graylog2#24]
Since this never calls `close` on the graylog2 UDP stream, this transport prevents the program from exiting when it's finished.

Here's some code I'm using to test:

``` coffeescript
winston = require('winston')
Graylog = require('winston-graylog2')

log = new(winston.Logger)(
  transports: [
    new (winston.transports.Console)(
      handleExceptions: true
    ),
    new(Graylog)(
      silent: false,
      handleExceptions: true,
      graylog:
        servers: [{host: '104.236.18.71', port: 12201}],
        bufferSize: 1400
    )
  ]
)

log.info('test')
```

**Comment by slang800** [comment]
a super hacky workaround for this would be reaching into the `graylog2` package & calling `unref()` on its client... something like

```coffeescript
setTimeout(( -> log.transports.graylog2.graylog2.client.unref()), 100)
```
But it needs to be run after the client has been created, which we can't determine reliably. Maybe this should be an issue with the graylog2 package

**Comment by unlucio** [comment]
hi @slang800 :)
yes, we saw that too but never really found an elegant way to make it happen yet :(
I saw you opened a PR to node-graylog2. I'll take a look and see if I can give an hand there :)

cheers

**Comment by odino** [comment]
@slang800 thumbs up if you want to give this a crack..we've been banging our head against it as well :)

**Comment by odino** [comment]
BTW we could do the same thing that's donw in https://github.com/kenperkins/winston-papertrail#closing-the-transport

**Comment by frehner** [comment]
A potentially interesting note is how this affects AWS Lambda functions, since they'll just time out instead of terminating -- and since you're charged for how long your Lambda function runs, it could cost you a bit more than you expect.
