### ISSUE TITLE
vulnerability warning from nsp

### ISSUE THREAD

**Issue by qamil** [namshi/winston-graylog2#25]
Output from nsp (https://nodesecurity.io/):
```
// Name  Installed  Patched  Vulnerable Dependency
qs      0.5.6     >= 1.x  klm-server@0.0.1 > winston-graylog2@0.2.2 > winston@0.7.3 > request@2.16.6 > qs@0.5.6
```
Worked around this issue by making a shrinkwrap and setting the version of qs to 1.0.0. It seems to work.

I think upgrading winston would fix this issue, but not sure if there are any vulnerabilities in a dependency deep in there. ;-)

**Comment by odino** [comment]
thanks @qamil! would you be able to send a PR? We can force newer versions in the package.json

**Comment by qamil** [comment]
@odino done :)
I'm not a seasoned winston/graylog user, but upgrading winston didn't break anything on my side.

**Comment by unlucio** [comment]
thanks @qamil !
