### ISSUE TITLE
winston should be in peerDependencies

### ISSUE THREAD

**Issue by henrikekblad** [namshi/winston-graylog2#31]
Like this:

package.json 

```
  "dependencies": {
    "graylog2": "^0.1.3",
    "lodash": "^3.1.0",
  },
  "peerDependencies": {
    "winston": "^1.0.0"
 }
```

Otherwise the graylog2 might drag in and use an older version of the winston library.

**Comment by odino** [comment]
hey @henrikekblad, thanks for reporting! Would you mind sending a PR? :)
