### ISSUE TITLE
graylog settings?

### ISSUE THREAD

**Issue by justechn** [namshi/winston-graylog2#32]
What input type should I be using in graylog

**Comment by justechn** [comment]
I have configured my graylog input to be GELF UDP. I have configured this app to use the same ip and port, but nothing is showing up in graylog.

What is the best way to debug this? is there a way to output exactly what this app is sending to graylog?

Can I turn on a verbose mode to see a stack trace? Anything to help me figure out why the messages are not getting to graylog?

**Comment by odino** [comment]
We have both TCP and UDP enabled, on the same port. Can you try sending a message to the server with `echo 'first log message' | nc localhost 5555` (where `5555` is the port GL is listening to)?

**Comment by justechn** [comment]
got this working.

**Comment by BrijToSuccess** [comment]
@justechn how did you get it to work?

**Comment by justechn** [comment]
sorry that was a long time ago and I don't remember.
