### ISSUE TITLE
Standardize code by using a linter and prettifier

### ISSUE THREAD

**Issue by urbanslug** [namshi/winston-graylog2#53]
Use a tool such as:
 * [eslint](https://www.npmjs.com/package/eslint) to have more standard code 
 * [prettier](https://www.npmjs.com/package/prettier) to have code that is more legible

This would make it easier for people who want to contribute and just easier to understand.

I suggest Google's eslint config because I feel it is more thorough thus leaving less room for bikeshedding.

**Comment by odino** [comment]
Hey @urbanslug thanks for raising this! I went ahead and merged your PR, I think it makes sense :)
