### ISSUE TITLE
Upgrade to es6

### ISSUE THREAD

**Issue by urbanslug** [namshi/winston-graylog2#55]
It would be nice and forward looking if we took advantage of some of the es6 features and wrote this code in a more functional way such as using arrow functions, const etc as well as fixing the current jsdoc annotations?

Some of that has already been done by using const for imports in PR https://github.com/namshi/winston-graylog2/pull/54.

**Comment by urbanslug** [comment]
Working on this here https://github.com/goodbotai/winston-graylog2/tree/55-upgrade-to-es6 would like feedback to abandon this effort early if there's no need for it according to the maintainer(s).

**Comment by urbanslug** [comment]
@odino ^ ?

**Comment by odino** [comment]
Already merged :) while we're not actively developing the library we're happy to have a look at contributions!

BTW, shameless plug, [we're hiring](http://tech.namshi.io/blog/2017/03/09/currently-hiring-backend-mobile-developers-dubai/) ;-)

**Comment by urbanslug** [comment]
This is a different issue and branch :smile: but I'll keep working on an ES6 upgrade when I have time.

I will look at your job ad for sure.

**Comment by schfkt** [comment]
It was done as part of https://github.com/namshi/winston-graylog2/pull/67
