### ISSUE TITLE
additional Fields 

### ISSUE THREAD

**Issue by OlmoDalco** [namshi/winston-graylog2#57]
According to the GELF Payload Specification _every field you send and prefix with an underscore (_) will be treated as an additional field._

Is there any chance to use this feature from within winston-graylog2 ?

**Comment by odino** [comment]
Hi @OlmoDalco!

Unfortunately, we dont actively support this library -- from the [readme](https://github.com/namshi/winston-graylog2#winston-graylog2):

```
LOOKING FOR A MAINTAINER!

Do you use / like this library? Reach out as we're looking for a maintainer -- we're not actively using this anymore and wouldn't mind leaving it in good hands :)
```

Will be very happy to have a look at PRs but, to be honest, I don't see us doing active development on the library going forward.
