### ISSUE TITLE
Adjust to winston 3.x transport API

### ISSUE THREAD

**Issue by philippmoehler0440** [namshi/winston-graylog2#58]
Hi,

since the release of Winston 3.0 there were some major changes of their API. Currently I`m getting this message with the use of graylog2 transport:

```
Kibana is a legacy winston transport. Consider upgrading:
    - Upgrade docs: https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md
```

If I got this right the adjustment has to be done within winston-graylog2.

Thank you and best regards
Philipp

**Comment by odino** [comment]
Hi @philippmoehler0440!

Unfortunately, we dont actively support this library -- from the [readme](https://github.com/namshi/winston-graylog2#winston-graylog2):

```
LOOKING FOR A MAINTAINER!

Do you use / like this library? Reach out as we're looking for a maintainer -- we're not actively using this anymore and wouldn't mind leaving it in good hands :)
```

Will be very happy to have a look at PRs but, to be honest, I don't see us doing active development on the library going forward.
