### ISSUE TITLE
I'd like to become a maintainer

### ISSUE THREAD

**Issue by schfkt** [namshi/winston-graylog2#60]
Hello guys. I noticed you're looking for a maintainer for this project. Me and my team -- we use it heavily in our projects. So it'd be great to maintain the lib, add more features, etc.

**Comment by odino** [comment]
Hi @schfkt -- thank for reaching out!

Before we hand the repo over we'd like you to interact a bit more -- feel free to send the initial PRs / enhancements and, once, a couple of them go through, we'd be happy to add you as a contributor, free of restrictions :)

Cheers and thanks again for showing up! :smile:

**Comment by odino** [comment]
Hey @schfkt -- you have now been added as a maintainer in the repo. You can push etc :)

The last step would involve giving you publish rights on the NPM registry -- let's hold on for a couple weeks and then I'll add you there as well!

**Comment by schfkt** [comment]
@odino thanks!
